services:
  - type: web
    name: siakad-mbs-poncowati
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: "20"
      - key: SESSION_SECRET
        generateValue: true
